name: Custom

# 适配 Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      # ==================== Kernel Version Configuration ====================
      android_version:
        description: "Android Version"
        required: true
        type: choice
        options:
          - android12
          - android13
          - android14
          - android15
          - android16
        default: android14
      kernel_version:
        description: "Kernel Version"
        required: true
        type: choice
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
          - "6.12"
        default: "6.1"
      sub_level:
        description: "Sublevel (eg. 66, 198, X)"
        required: true
        type: string
        default: "157"
      os_patch_level:
        description: "OS Patch Level (eg. 2022-01, lts)"
        required: true
        type: string
        default: "2025-12"
      revision:
        description: "Revision (eg. r11, 5.10 only)"
        required: false
        type: string
        default: ""

      # ==================== KernelSU configuration ====================
      # KernelSU fork set to ReSukiSU
      kernelsu_branch:
        description: "KSU branch (main/builtin/commit hash)"
        required: false
        type: string
        default: ""

      # ==================== Optional configurations ====================
      version:
        description: "Custom Version Name"
        required: false
        type: string
      build_time:
        description: "Custom Build Time"
        required: false
        type: string
        default: "Sun Mar 22 08:10:00 UTC 2026"

      # ==================== Features ====================
      use_zram:
        description: "Enable ZRAM"
        required: true
        type: boolean
        default: false
      use_bbg:
        description: "Enable BBG"
        required: true
        type: boolean
        default: true
      use_rekernel:
        description: "Enable Re-Kernel"
        required: false
        type: boolean
        default: false
      cancel_susfs:
        description: "Disable SUSFS"
        required: true
        type: boolean
        default: true
      enable_nomount:
        description: "Enable NoMount"
        required: true
        type: boolean
        default: true
      supp_op:
        description: "Enable Support for OP 8E"
        required: false
        type: boolean
        default: false
      droidspaces:
        description: "Droidspaces support"
        required: false
        type: choice
        options:
          - "off"
          - "678"
          - "123"
          - "345"
        default: "off"
      droidspaces_ntsync:
        description: "Enable Droidspaces NTSync"
        required: false
        type: boolean
        default: false

jobs:
  build-custom-kernel:
    name: "${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ inputs.android_version }}-${{ inputs.os_patch_level }}"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ inputs.android_version }}
      kernel_version: ${{ inputs.kernel_version }}
      sub_level: ${{ inputs.sub_level }}
      os_patch_level: ${{ inputs.os_patch_level }}
      revision: ${{ inputs.revision || '' }}
      ksu_variant: "ReSukiSU"
      ksu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version || '' }}
      build_time: ${{ inputs.build_time || '' }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_rekernel: ${{ inputs.use_rekernel || false }}
      supp_op: ${{ inputs.supp_op || false }}
      enable_susfs: ${{ !inputs.cancel_susfs }}
      enable_nomount: ${{ inputs.enable_nomount  || false }}
      droidspaces: ${{ inputs.droidspaces || 'off' }}
      droidspaces_ntsync: ${{ inputs.droidspaces_ntsync || false }}

  get-ksu-manager:
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
